#!/usr/bin/env bash

# Script to stow all configs

declare -a CONFIGS=("tmux"
                    "vim"
                    "polybar"
                    "alacritty"
                    "i3"
                    "nvim"
                    "git"
                    "zsh")

for config in "${CONFIGS[@]}"; do
    stow $config
    echo "Stowing "$config
done
exit
